---

- block:
  - validate:
      schema:
        type: object
        additionalProperties:
          - command
        properties:
          name:
            type: string
            default: "{{ inventory_hostname }}"
          project:
            type: string
          state:
            type: string
            enum:
              - started
              - stopped
          zone:
            type: string
        required:
          - name
          - project
          - state
          - zone
      instance: "{{ gcp }}"
    register: gcp_validated

  - set_fact:
      gcp_v: "{{ gcp_validated.result }}"

  - name: "Flush handlers before shutdown"
    meta: flush_handlers

  - name: "Control instance {{ gcp_v.name }}: {{ gcp_v.state }}"
    command: "gcloud compute instances {{ (gcp_v.state == 'started') | ternary('start', 'stop') }} {{ gcp_v.name }} --zone={{ gcp_v.zone }} --project={{ gcp_v.project }}"
    delegate_to: localhost

  - name: "Wait for the SSH connection to return"
    wait_for_connection:
      timeout: 240
      delay: 10
    when: gcp_v.state == 'started'

  tags:
    - gcp_control_instance