---

- block:
  - validate:
      schema:
        type: object
        additionalProperties:
          - command
        properties:
          keys:
            type: array
            items:
              type: object
              additionalProperties: no
              properties:
                username:
                  type: string
                  pattern: ^[a-z_][a-z0-9_]{0,29}$
                key_type:
                  type: string
                  enum:
                    - ssh-ed25519
                    - ssh-rsa
                key_data:
                  type: string
                comment:
                  type: string
              required:
                - username
                - key_type
                - key_data
                - comment
            minItems: 1
            uniqueItems: yes
          project:
            type: string
        required:
          - keys
          - project
      instance: "{{ gcp }}"
    register: gcp_validated

  - set_fact:
      gcp_v: "{{ gcp_validated.result }}"

  - project_ssh_keys:
      keys: "{{ gcp_v.keys }}"
      project: "{{ gcp_v.project }}"
  tags:
    - gcp_project_ssh_keys