---

- block:
  - validate:
      schema:
        type: object
        additionalProperties:
          - command
        properties:
          address_range:
            type: string
            format: ipv4

          auth_kind:
            type: string
            enum:
              - application
              - serviceaccount
            default: application

          name_prefix:
            type: string
            pattern: ^[a-z0-9-]+$

          project:
            type: string

          region:
            type: string
                
          state:
            type: string
            default: present
            enum:
              - absent
              - present

          vpc_network:
            type: string
            pattern: ^[a-z0-9/-]+$

        required:
          - address_range
          - auth_kind
          - name_prefix
          - project
          - region
          - state
          - vpc_network

      instance: "{{ gcp }}"
    register: gcp_validated

  - set_fact:
      gcp_v: "{{ gcp_validated.result }}"

  - name: "Deploy Subnetwork {{ gcp_v.name_prefix }}-{{ gcp_v.region }}: {{ gcp_v.state }}"
    gcp_deployment:
      auth_kind: "{{ gcp_v.auth_kind }}"
      config:
        resources: 
        - name: "{{ gcp_v.name_prefix }}-{{ gcp_v.region }}"
          type: compute.v1.subnetwork
          properties:
            name: "{{ gcp_v.name_prefix }}-{{ gcp_v.region }}"
            ipCidrRange: "{{ gcp_v.address_range }}"
            region: "{{ gcp_v.region }}"
            network: "{{ gcp_v.vpc_network }}"
      name: "subnetwork-{{ gcp_v.name_prefix }}-{{ gcp_v.region }}"
      project: "{{ gcp_v.project }}"
      state: "{{ gcp_v.state }}"
  tags:
    - gcp_subnetwork